language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - main
deploy:
  provider: heroku
  app: clicker-game-1
  api_key:
    secure: GFVzqOtpjtAEeEkZtJS214UabiN/a8ucxbj5RltfU+UbWCfr3EvxZWqPlRKvlvDHC1ZIfLJSqwzvyKHvq7X7CAyVZViaNngeCU/Rz5Xo4bllvac0VLtR361tVcP08TSFDn1wZNx2Dm5Lb6HH2SjEer+N1mlvM/oEjVGaZir6zJfwYsuA/VEX3VHThg7/f9wJdPfbxkp9nXXOc2CeLBgmkyAwIVE5TsTUo9SHNUrJMAOHho2NZ3YziMLKyxTB4aQJIYAA55DpOBiLmxhHLUMgOs3RA3L/Vby2axUhlGv7/+fyy0FFoBN7sMspnMab4L53HHlz3nb5q2Pte2FTmASJ76AAdGysBlKlhgn6TQFgX6lZEfhb78rMsVdljnvca5pjvz9oazbbEGTJ+eTuqbszaa6xBoGmOj9/ebp99LZOXfvlhVy/FV2hdfMKOnjsxAEfym+TtfYvau+dxxLxQ7ZN6JN4xOXXPzKXvP7cuH7vM95H1Fn6dId7QxosEStPbMjXQ2hRsYdczZNl1K5JTErHkapRJQ0rS/I/1/YvLY4aEW4XEsVJxSdNoFbqtdAvXVY9w7q+xG1NNB7HsqeLEyr8YKvEpZGiUh+SoedhtHbsKm1kc0NhZCpFDAzhoXMWUeupfMMyPe5h2ilx24sYjU3lmLyj4kCmxzm+AO5yY0J50v8=
  on:
    branch:
    - main
