language: node_js
node_js:
- '10'
before_install:
- npm install -g @angular/cli
install: npm install
branches:
  only:
  - main
deploy:
  provider: heroku
  app: clicker-game-1
  api_key:
    secure: QJqRfie8rNCaZZ7rrW40OW5ttLVWMJQUuexBimF+TxYECe82SRVhV++IRr1gyEor63NyuYxYD+QWDOAhSgh+C2QpsYSaTUfWTUXEoacJr/m2BnwfaFgYNgKK6M+jDZMBUdY+qfS/LkftfLexq7GJMeTwOR0orntGNUc/OD8JAMvOdCNyQxE3ru6O8RTTrwFsh9NQTnEzbZ4z1KrJGaa7mln6/BlPaP975DTWINJdAs7mEOTqWolPVxiDtF1JqSmevkrjWS8kzdoyNyVDsOKa48TT6bPw28JXQ/cmFVsBepKc8A8Z1VNdpR5fDRK+h9xsaJtztc3QOVzd6lqpq4ZQIRxzAItVsTfKA0JITqJaikvDg/zJ0Mu+ksdqV6u2IBMbQqdozv3k2kdZrUqc0TsV4NsRixEUa5l9QzOXtbC0cvS56mvDd8h+g9e4oSLlkJmzkR9nCHeACFfkdrlzad0zOJsH9D7HhrNoMMaJSwqWquBHmHtx/C0R/Qg2M8nEKpvKHwHq51fXEL0p75Rs187LH2M4S4qOs7xLR0pYyX/FCdnA4suLaGeeZlLGST4aCrDbb7utW1U6ctZjdRNajuphml+KvG6sr13+9TArTY6FORTNd7jlUYN71K89UGHcghgOWhK98kxH8mBx3lSP386JpJKzGNIyG+Ji72iMtOSewg4=
  on:
    branch:
    - main
